file=open('test.txt', 'r')
print(file.read())
file.close()
file=open('test.txt', 'r')
print('Read first 50 characters')
print(file.read(50))
file.close()
file=open('test.txt', 'w')
file.write("Music is a universal language that transcends cultural and geographical boundaries, serving as a powerful medium for emotional expression and social connection")
file.close()
file=open('test.txt', 'a')
file.write("Music comprises sound, melody, rhythm, harmony, and structure, which combine to create an immersive experience")
file.close()
