line=input("Enter your three favourite movie names: ")
print(line)
print(line[0])
print(line[1])
print(line[2])
print(line[3])
print(line[4])
print(line[5])
print(line[6])
print(line[7])
print(line[0:8])
print(line[0:8:1])
print(line[0:8:2])
print(line[0:8:3])
print(line[1:8:2])
print(line[::-1])